title: PenPointPoke
author: Samarth Anand
email: 201851108@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there! Always desired that people read between my lines. I can see my dream coming true.
  Excited ??  YeSSSS!!!

# social links
twitter_username: SamarthAlways # DO NOT include the @ character, or else the build will fail!
github_username:  SamarthAnand # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
